// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[section]/[title].tsx";
import * as $1 from "./routes/[section]/index.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Post.tsx";

const manifest = {
  routes: {
    "./routes/[section]/[title].tsx": $0,
    "./routes/[section]/index.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Post.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
